### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by baimurzin** [nikit-cpp/good-parts#1]
How to restart all of this if I ran **docker stack deploy** and **docker scale**.
I changed one config and want to restart it. What I should do locally?

P.S. btw, a very great codebase and blog solution. But I misunderstood why are you doing this?

**Comment by nkonev** [comment]
@baimurzin 

Hmm, I never restart all of this.

If you has changed application.yml you should re-build container with docker build ... It's too complex.
For avoid this I placed most changeable properties in docker-compose.template.yml
In this case I remove BLOGSTACK_blog service
```
docker service remove BLOGSTACK_blog
```
And apply docker-compose.template.yml to swarm again:
```
docker stack deploy --compose-file docker-compose.template.yml BLOGSTACK
```
This command will re-create containers with new [environment variables](https://12factor.net/config) which have [more priority](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html) than counterarts in application.yml
